---
- name: "Load OS-specific variables"
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
  
- name: "Update package cache and upgrade system"
  become: true
  ansible.builtin.package:
    update_cache: yes
    upgrade: yes

- name: "Install base and development tool packages"
  become: true
  ansible.builtin.package:
    name: "{{ base_packages + devtools_packages }}"
    state: present