---
- name: "PYTHON | Load OS-specific variables"
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: "PYTHON | Install Python tools (pip, venv, pipx)"
  become: true
  ansible.builtin.package:
    name: "{{ python_packages }}"
    state: present

- name: "PYTHON | Ensure pipx path is in the shell config"
  blockinfile:
    path: "{{ shell_config_file }}"
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK - pipx"
    block: |
      # Add pipx-installed packages to the PATH
      export PATH="$PATH:{{ user_home }}/.local/bin"