---
- name: "Load OS-specific variables"
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
  
- name: "Install Java SDK"
  become: true
  ansible.builtin.package:
    name: "{{ java_package_name }}"
    state: present